INSERT INTO role (ID, NAME)
VALUES (1, 'ROLE_USER');

INSERT INTO role (ID, NAME)
VALUES (2, 'ROLE_ADMIN');

INSERT INTO users (ID, FIRST_NAME, LAST_NAME, PASSWORD, PHONE_NUMBER, USERNAME, ROLE_ID)
VALUES (1, 'Pera', 'Peric', '$2a$10$28MUwyYgna28OIxoUnE7VOpjby0JRJUU0WQV0UZdMX5XA46XAvBCK', '+329032032', 'peraperic', 2);

INSERT INTO users (ID, FIRST_NAME, LAST_NAME, PASSWORD, PHONE_NUMBER, USERNAME, ROLE_ID)
VALUES (2, 'Toma', 'Tomic', '$2a$10$28MUwyYgna28OIxoUnE7VOpjby0JRJUU0WQV0UZdMX5XA46XAvBCK', '+32323232', 'tomatomic', 1);

INSERT INTO users (ID, FIRST_NAME, LAST_NAME, PASSWORD, PHONE_NUMBER, USERNAME, ROLE_ID)
VALUES (3, 'Steva', 'Stevic', '$2a$10$28MUwyYgna28OIxoUnE7VOpjby0JRJUU0WQV0UZdMX5XA46XAvBCK', '+2342332', 'stevastevic', 1);

